ccproject/ccproject/Controllers/CrudMvcController.cs
using ccproject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ccproject.Controllers
{
    public class CrudMvcController : Controller
    {
        HttpClient client = new HttpClient();

        public ActionResult Index()

        {

            List<Service> emp_list = new List<Service>();

            client.BaseAddress = new Uri("https://localhost:44344/api/CrudApi");
            var response = client.GetAsync("CrudApi");
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<List<Service>>();
                display.Wait();
                emp_list = display.Result;
            }
            return View(emp_list);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Service ad)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/CrudApi");
            var response = client.PostAsJsonAsync<Service>("CrudApi", ad);
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Create");
        }
        public ActionResult Details(int ID)
        {
            Service a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/CrudApi");
            var response = client.GetAsync("CrudApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Service>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        public ActionResult Edit(int ID)
        {
            Service a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/CrudApi");
            var response = client.GetAsync("CrudApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Service>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        [HttpPost]
        public ActionResult Edit(Service e)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/CrudApi");
            var response = client.PutAsJsonAsync<Service>("CrudApi", e);
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Edit");
        }
        public ActionResult Delete(int ID)
        {
            Service a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/CrudApi");
            var response = client.GetAsync("CrudApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Service>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int ID)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/CrudApi");
            var response = client.DeleteAsync("CrudApi/" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Delete");


        }
    }
}

ccproject/ccproject/Controllers/LoginController.cs
using ccproject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ccproject.Controllers
{
    public class LoginController : Controller
    {
        ccobjEntities2 db = new ccobjEntities2();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(user u)
        {
            var user = db.users.Where(model => model.username == u.username && model.password == u.password).FirstOrDefault();
            if (user != null)
            {
                Session["UserId"] = u.Id.ToString();
                Session["Username"] = u.username.ToString();
                TempData["LoginSuccessMessage"] = "<script>alert('Login successfull!')</script>";
                if (u.username == "Admin" && u.password == "123")
                {
                    return RedirectToAction("Admindashboard", "Dashboards");
                }
                else
                {
                    return RedirectToAction("Userdashboard", "Dashboards");
                }
            }
            else
            {
                ViewBag.ErrorMessage = "<script>alert('Username or Password is incorrect!')</script>";
                return View();
            }

        }
        public ActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Signup(user u)
        {
            if (ModelState.IsValid == true)
            {
                db.users.Add(u);
                int a = db.SaveChanges();
                if (a > 0)
                {
                    ViewBag.InsertMessage = "<script>alert('Registered Successfully')</script>";
                    ModelState.Clear();
                }
                else
                {
                    ViewBag.InsertMessage = "<script>alert('Registeration failed')</script>";
                }
            }
            return View();
        }
    }
}

ccproject/ccproject/Controllers/PaymentMvcController.cs
using ccproject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ccproject.Controllers
{
    public class PaymentMvcController : Controller
    {
        HttpClient client = new HttpClient();

        public ActionResult Index()

        {

            List<Payment> emp_list = new List<Payment>();

            client.BaseAddress = new Uri("https://localhost:44344/api/PaymentApi");
            var response = client.GetAsync("PaymentApi");
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<List<Payment>>();
                display.Wait();
                emp_list = display.Result;
            }
            return View(emp_list);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Payment ad)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/PaymentApi");
            var response = client.PostAsJsonAsync<Payment>("PaymentApi", ad);
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Create");
        }
        public ActionResult Details(int ID)
        {
            Payment a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/PaymentApi");
            var response = client.GetAsync("PaymentApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Payment>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        public ActionResult Edit(int ID)
        {
            Payment a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/PaymentApi");
            var response = client.GetAsync("PaymentApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Payment>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        [HttpPost]
        public ActionResult Edit(Payment e)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/PaymentApi");
            var response = client.PutAsJsonAsync<Payment>("PaymentApi", e);
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Edit");
        }
        public ActionResult Delete(int ID)
        {
            Payment a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/PaymentApi");
            var response = client.GetAsync("PaymentApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Payment>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int ID)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/PaymentApi");
            var response = client.DeleteAsync("PaymentApi/" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Delete");


        }
    }
}

ccproject/ccproject/Controllers/ProductMvcController.cs
using ccproject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ccproject.Controllers
{
    public class ProductMvcController : Controller
    {
        HttpClient client = new HttpClient();

        public ActionResult Index()

        {

            List<Product> emp_list = new List<Product>();

            client.BaseAddress = new Uri("https://localhost:44344/api/ProductApi");
            var response = client.GetAsync("ProductApi");
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<List<Product>>();
                display.Wait();
                emp_list = display.Result;
            }
            return View(emp_list);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product ad)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/ProductApi");
            var response = client.PostAsJsonAsync<Product>("ProductApi", ad);
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Create");
        }
        public ActionResult Details(int ID)
        {
            Product a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/ProductApi");
            var response = client.GetAsync("ProductApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Product>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        public ActionResult Edit(int ID)
        {
            Product a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/ProductApi");
            var response = client.GetAsync("ProductApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Product>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        [HttpPost]
        public ActionResult Edit(Product e)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/ProductApi");
            var response = client.PutAsJsonAsync<Product>("ProductApi", e);
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Edit");
        }
        public ActionResult Delete(int ID)
        {
            Product a = null;
            client.BaseAddress = new Uri("https://localhost:44344/api/ProductApi");
            var response = client.GetAsync("ProductApi?ID=" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Product>();
                display.Wait();
                a = display.Result;
            }

            return View(a);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int ID)
        {
            client.BaseAddress = new Uri("https://localhost:44344/api/ProductApi");
            var response = client.DeleteAsync("ProductApi/" + ID.ToString());
            response.Wait();
            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Delete");


        }
    }
}

ccproject/ccproject/Views/Shared/Admindashlayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Azad Traders</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css'>
    <style>
        .wrapper .icon {
            position: relative;
            background-color: #ffffff;
            border-radius: 50%;
            margin: 10px;
            width: 50px;
            height: 50px;
            line-height: 50px;
            font-size: 22px;
            display: inline-block;
            align-items: center;
            box-shadow: 0 10px 10px rgba(0, 0, 0, 0.1);
            cursor: pointer;
            transition: all 0.2s cubic-bezier(0.68, -0.55, 0.265, 1.55);
            color: #333;
            text-decoration: none;
        }

        .wrapper .tooltip {
            position: absolute;
            top: 0;
            line-height: 1.5;
            font-size: 14px;
            background-color: #ffffff;
            color: #ffffff;
            padding: 5px 8px;
            border-radius: 5px;
            box-shadow: 0 10px 10px rgba(0, 0, 0, 0.1);
            opacity: 0;
            pointer-events: none;
            transition: all 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
        }

            .wrapper .tooltip::before {
                position: absolute;
                content: "";
                height: 8px;
                width: 8px;
                background-color: #ffffff;
                bottom: -3px;
                left: 50%;
                transform: translate(-50%) rotate(45deg);
                transition: all 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
            }

        .wrapper .icon:hover .tooltip {
            top: -45px;
            opacity: 1;
            visibility: visible;
            pointer-events: auto;
        }

        .wrapper .icon:hover span,
        .wrapper .icon:hover .tooltip {
            text-shadow: 0px -1px 0px rgba(0, 0, 0, 0.1);
        }

        .wrapper .facebook:hover,
        .wrapper .facebook:hover .tooltip,
        .wrapper .facebook:hover .tooltip::before {
            background-color: #3b5999;
            color: #ffffff;
        }

        .wrapper .twitter:hover,
        .wrapper .twitter:hover .tooltip,
        .wrapper .twitter:hover .tooltip::before {
            background-color: #46c1f6;
            color: #ffffff;
        }

        .wrapper .instagram:hover,
        .wrapper .instagram:hover .tooltip,
        .wrapper .instagram:hover .tooltip::before {
            background-color: #e1306c;
            color: #ffffff;
        }

        .wrapper .github:hover,
        .wrapper .github:hover .tooltip,
        .wrapper .github:hover .tooltip::before {
            background-color: #333333;
            color: #ffffff;
        }

        .wrapper .youtube:hover,
        .wrapper .youtube:hover .tooltip,
        .wrapper .youtube:hover .tooltip::before {
            background-color: #de463b;
            color: #ffffff;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:purple;color:white">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GlowGlam", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Admindashboard", "Dashboards")</li>
                    <li>@Html.ActionLink("Customers", "Index", "CustomerMvc")</li>
                    <li>@Html.ActionLink("Employees", "Index", "EmployeeMvc")</li>
                    <li>@Html.ActionLink("Products", "Index", "ProductMvc")</li>
                    <li>@Html.ActionLink("Services", "Index", "CrudMvc")</li>
                    <li>@Html.ActionLink("Appointments", "Index", "AppointmentMvc")</li>
                    <li>@Html.ActionLink("Payments", "Index", "PaymentMvc")</li>
                    <li>@Html.ActionLink("Logout", "Index", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="navbar navbar-inverse navbar-fixed-bottom" style="background-color:purple;color:white">
                <div class="container">
                    <div class="navbar-header">
                        <center>
                            <div class="wrapper">
                                <center>
                                    <a href="https://www.facebook.com/GLAMGLOWOfficial/" class="icon facebook">
                                        <div class="tooltip">Facebook</div>
                                        <span><i class="fab fa-facebook-f"></i></span>
                                    </a>
                                    <a href="https://twitter.com/glamglowph?lang=en" class="icon twitter">
                                        <div class="tooltip">Twitter</div>
                                        <span><i class="fab fa-twitter"></i></span>
                                    </a>
                                    <a href="https://www.instagram.com/the_glowglam/?hl=en" class="icon instagram">
                                        <div class="tooltip">Instagram</div>
                                        <span><i class="fab fa-instagram"></i></span>
                                    </a>

                                    <a href="https://www.youtube.com/channel/UCpmq5Vaz8uoDqT6XJFgafrA" class="icon youtube">
                                        <div class="tooltip">Youtube</div>
                                        <span><i class="fab fa-youtube"></i></span>
                                    </a>
                                </center>
                            </div>

                    </div></center>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                        </ul>
                    </div>
                </div>
            </div>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ccproject/ccproject/Views/Shared/Userdashlayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Azad Traders</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css'>
    <style>
        .wrapper .icon {
            position: relative;
            background-color: #ffffff;
            border-radius: 50%;
            margin: 10px;
            width: 50px;
            height: 50px;
            line-height: 50px;
            font-size: 22px;
            display: inline-block;
            align-items: center;
            box-shadow: 0 10px 10px rgba(0, 0, 0, 0.1);
            cursor: pointer;
            transition: all 0.2s cubic-bezier(0.68, -0.55, 0.265, 1.55);
            color: #333;
            text-decoration: none;
        }

        .wrapper .tooltip {
            position: absolute;
            top: 0;
            line-height: 1.5;
            font-size: 14px;
            background-color: #ffffff;
            color: #ffffff;
            padding: 5px 8px;
            border-radius: 5px;
            box-shadow: 0 10px 10px rgba(0, 0, 0, 0.1);
            opacity: 0;
            pointer-events: none;
            transition: all 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
        }

            .wrapper .tooltip::before {
                position: absolute;
                content: "";
                height: 8px;
                width: 8px;
                background-color: #ffffff;
                bottom: -3px;
                left: 50%;
                transform: translate(-50%) rotate(45deg);
                transition: all 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
            }

        .wrapper .icon:hover .tooltip {
            top: -45px;
            opacity: 1;
            visibility: visible;
            pointer-events: auto;
        }

        .wrapper .icon:hover span,
        .wrapper .icon:hover .tooltip {
            text-shadow: 0px -1px 0px rgba(0, 0, 0, 0.1);
        }

        .wrapper .facebook:hover,
        .wrapper .facebook:hover .tooltip,
        .wrapper .facebook:hover .tooltip::before {
            background-color: #3b5999;
            color: #ffffff;
        }

        .wrapper .twitter:hover,
        .wrapper .twitter:hover .tooltip,
        .wrapper .twitter:hover .tooltip::before {
            background-color: #46c1f6;
            color: #ffffff;
        }

        .wrapper .instagram:hover,
        .wrapper .instagram:hover .tooltip,
        .wrapper .instagram:hover .tooltip::before {
            background-color: #e1306c;
            color: #ffffff;
        }

        .wrapper .github:hover,
        .wrapper .github:hover .tooltip,
        .wrapper .github:hover .tooltip::before {
            background-color: #333333;
            color: #ffffff;
        }

        .wrapper .youtube:hover,
        .wrapper .youtube:hover .tooltip,
        .wrapper .youtube:hover .tooltip::before {
            background-color: #de463b;
            color: #ffffff;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:purple;color:white">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GlowGlam", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Userdashboard", "Dashboards")</li>
                    <li>@Html.ActionLink("Products", "Index", "UProductMvc")</li>
                    <li>@Html.ActionLink("Services", "Index", "UServiceMvc")</li>
                    <li>@Html.ActionLink("Appointments", "Index", "UAppointmentMvc")</li>
                    <li>@Html.ActionLink("Payments", "Index", "UPaymentMvc")</li>
                    <li>@Html.ActionLink("Logout", "Index", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="navbar navbar-inverse navbar-fixed-bottom" style="background-color:purple;color:white">
                <div class="container">
                    <div class="navbar-header">
                        <center>
                            <div class="wrapper">
                                <center>
                                    <a href="https://www.facebook.com/GLAMGLOWOfficial/" class="icon facebook">
                                        <div class="tooltip">Facebook</div>
                                        <span><i class="fab fa-facebook-f"></i></span>
                                    </a>
                                    <a href="https://twitter.com/glamglowph?lang=en" class="icon twitter">
                                        <div class="tooltip">Twitter</div>
                                        <span><i class="fab fa-twitter"></i></span>
                                    </a>
                                    <a href="https://www.instagram.com/the_glowglam/?hl=en" class="icon instagram">
                                        <div class="tooltip">Instagram</div>
                                        <span><i class="fab fa-instagram"></i></span>
                                    </a>

                                    <a href="https://www.youtube.com/channel/UCpmq5Vaz8uoDqT6XJFgafrA" class="icon youtube">
                                        <div class="tooltip">Youtube</div>
                                        <span><i class="fab fa-youtube"></i></span>
                                    </a>
                                </center>
                            </div>

                    </div></center>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                        </ul>
                    </div>
                </div>
            </div>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ccproject/ccproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Login", "Index", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>